version: "3.9"
services:
  mariadb:
    image: mariadb:11.7.2
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=postal
      - MARIADB_ROOT_PASSWORD=postal
      - MARIADB_ROOT_HOST=%
    command: --innodb-log-file-size=256M
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppostal"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "127.0.0.1:3306:3306"

  rabbitmq:
    image: rabbitmq:3.9
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=postal
      - RABBITMQ_DEFAULT_PASS=postal
      - RABBITMQ_DEFAULT_VHOST=postal
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    image: ghcr.io/postalserver/postal:3.3.4
    command: postal web-server
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - POSTAL_SIGNING_KEY_PATH=/config/signing.key
      - MAIN_DB_HOST=mariadb
      - MAIN_DB_USERNAME=root
      - MAIN_DB_PASSWORD=postal
      - MESSAGE_DB_HOST=mariadb
      - MESSAGE_DB_USERNAME=root
      - MESSAGE_DB_PASSWORD=postal
      - POSTAL_WEB_HOST=${POSTAL_WEB_HOST:-postal.yourdomain.com}
      - POSTAL_WEB_PROTOCOL=${POSTAL_WEB_PROTOCOL:-https}
      - POSTAL_SECRET_KEY=${POSTAL_SECRET_KEY:-supersecretkey12345}
      - WEB_SERVER_BIND_ADDRESS=0.0.0.0
      - WEB_SERVER_PORT=5000
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=postal
      - RABBITMQ_PASSWORD=postal
      - RABBITMQ_VHOST=postal
    volumes:
      - postal_config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  smtp:
    image: ghcr.io/postalserver/postal:3.3.4
    command: postal smtp-server
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "25:25"
    environment:
      - POSTAL_SIGNING_KEY_PATH=/config/signing.key
      - MAIN_DB_HOST=mariadb
      - MAIN_DB_USERNAME=root
      - MAIN_DB_PASSWORD=postal
      - MESSAGE_DB_HOST=mariadb
      - MESSAGE_DB_USERNAME=root
      - MESSAGE_DB_PASSWORD=postal
      - POSTAL_WEB_HOST=${POSTAL_WEB_HOST:-postal.yourdomain.com}
      - POSTAL_WEB_PROTOCOL=${POSTAL_WEB_PROTOCOL:-https}
      - POSTAL_SECRET_KEY=${POSTAL_SECRET_KEY:-supersecretkey12345}
      - SMTP_SERVER_BIND_ADDRESS=0.0.0.0
      - SMTP_SERVER_PORT=25
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=postal
      - RABBITMQ_PASSWORD=postal
      - RABBITMQ_VHOST=postal
    volumes:
      - postal_config:/config
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "25"]
      interval: 10s
      timeout: 5s
      retries: 3

  worker1:
    image: ghcr.io/postalserver/postal:3.3.4
    command: postal worker
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - POSTAL_SIGNING_KEY_PATH=/config/signing.key
      - MAIN_DB_HOST=mariadb
      - MAIN_DB_USERNAME=root
      - MAIN_DB_PASSWORD=postal
      - MESSAGE_DB_HOST=mariadb
      - MESSAGE_DB_USERNAME=root
      - MESSAGE_DB_PASSWORD=postal
      - POSTAL_WEB_HOST=${POSTAL_WEB_HOST:-postal.yourdomain.com}
      - POSTAL_WEB_PROTOCOL=${POSTAL_WEB_PROTOCOL:-https}
      - POSTAL_SECRET_KEY=${POSTAL_SECRET_KEY:-supersecretkey12345}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=postal
      - RABBITMQ_PASSWORD=postal
      - RABBITMQ_VHOST=postal
    volumes:
      - postal_config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  worker2:
    image: ghcr.io/postalserver/postal:3.3.4
    command: postal worker
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - POSTAL_SIGNING_KEY_PATH=/config/signing.key
      - MAIN_DB_HOST=mariadb
      - MAIN_DB_USERNAME=root
      - MAIN_DB_PASSWORD=postal
      - MESSAGE_DB_HOST=mariadb
      - MESSAGE_DB_USERNAME=root
      - MESSAGE_DB_PASSWORD=postal
      - POSTAL_WEB_HOST=${POSTAL_WEB_HOST:-postal.yourdomain.com}
      - POSTAL_WEB_PROTOCOL=${POSTAL_WEB_PROTOCOL:-https}
      - POSTAL_SECRET_KEY=${POSTAL_SECRET_KEY:-supersecretkey12345}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=postal
      - RABBITMQ_PASSWORD=postal
      - RABBITMQ_VHOST=postal
    volumes:
      - postal_config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  cron:
    image: ghcr.io/postalserver/postal:3.3.4
    command: postal cron
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - POSTAL_SIGNING_KEY_PATH=/config/signing.key
      - MAIN_DB_HOST=mariadb
      - MAIN_DB_USERNAME=root
      - MAIN_DB_PASSWORD=postal
      - MESSAGE_DB_HOST=mariadb
      - MESSAGE_DB_USERNAME=root
      - MESSAGE_DB_PASSWORD=postal
      - POSTAL_WEB_HOST=${POSTAL_WEB_HOST:-postal.yourdomain.com}
      - POSTAL_WEB_PROTOCOL=${POSTAL_WEB_PROTOCOL:-https}
      - POSTAL_SECRET_KEY=${POSTAL_SECRET_KEY:-supersecretkey12345}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=postal
      - RABBITMQ_PASSWORD=postal
      - RABBITMQ_VHOST=postal
    volumes:
      - postal_config:/config

  init:
    image: ghcr.io/postalserver/postal:3.3.4
    command: ["bash", "-c", "until nc -z mariadb 3306 && nc -z rabbitmq 5672; do sleep 1; done && postal initialize || true"]
    depends_on:
      - mariadb
      - rabbitmq
    restart: "no"
    environment:
      - POSTAL_SIGNING_KEY_PATH=/config/signing.key
      - MAIN_DB_HOST=mariadb
      - MAIN_DB_USERNAME=root
      - MAIN_DB_PASSWORD=postal
      - MESSAGE_DB_HOST=mariadb
      - MESSAGE_DB_USERNAME=root
      - MESSAGE_DB_PASSWORD=postal
      - POSTAL_WEB_HOST=${POSTAL_WEB_HOST:-postal.yourdomain.com}
      - POSTAL_WEB_PROTOCOL=${POSTAL_WEB_PROTOCOL:-https}
      - POSTAL_SECRET_KEY=${POSTAL_SECRET_KEY:-supersecretkey12345}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=postal
      - RABBITMQ_PASSWORD=postal
      - RABBITMQ_VHOST=postal
    volumes:
      - postal_config:/config

volumes:
  postal_config:
  mariadb_data:
  rabbitmq_data:
