version: "3"
services:
  postal:
    build:
      context: .
      target: full
    depends_on:
      - mariadb
    entrypoint: ["/docker-entrypoint.sh"]
    command: ["postal", "web-server", "--bind-address=0.0.0.0"]
    environment:
      POSTAL_SIGNING_KEY_PATH: /config/signing.key
      MAIN_DB_HOST: mariadb
      MAIN_DB_USERNAME: root
      MESSAGE_DB_HOST: mariadb
      MESSAGE_DB_USERNAME: root
      RAILS_ENVIRONMENT: production
      RAILS_LOG_ENABLED: "true"
      POSTAL_WEB_HOST: bakra.postal.pdevsecops.com
      POSTAL_WEB_PROTOCOL: https
      POSTAL_SMTP_PORT: 25
      POSTAL_WEB_PORT: 5000
      POSTAL_SECRET_KEY: supersecretkey12345
    ports:
      - "5000:5000"
      - "25:25"
    restart: unless-stopped

  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: postal
      MARIADB_ALLOW_EMPTY_PASSWORD: 'yes'
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
