version: "3"
services:
  postal:
    image: ghcr.io/postalserver/postal:latest
    depends_on:
      - mariadb
    restart: always
    ports:
      - "5000:5000"
      - "25:25"
    environment:
      - POSTAL_SIGNING_KEY_PATH=/config/signing.key
      - MAIN_DB_HOST=mariadb
      - MAIN_DB_USERNAME=root
      - MAIN_DB_PASSWORD=
      - MESSAGE_DB_HOST=mariadb
      - MESSAGE_DB_USERNAME=root
      - MESSAGE_DB_PASSWORD=
      - POSTAL_WEB_HOST=${POSTAL_WEB_HOST}
      - POSTAL_WEB_PROTOCOL=${POSTAL_WEB_PROTOCOL}
      - POSTAL_SECRET_KEY=${POSTAL_SECRET_KEY}
    volumes:
      - postal_config:/config

  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      - MARIADB_DATABASE=postal
      - MARIADB_ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    command: --innodb-log-file-size=256M
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  postal_config:
  mariadb_data:
