version: "3"
services:
  postal:
    build:
      context: .
      target: full
    depends_on:
      - mariadb
    entrypoint: ["/docker-entrypoint.sh"]
    command: ["bash", "-c", "postal initialize && postal web-server"]
    volumes:
      - "./docker/ci-config:/config"
    environment:
      POSTAL_SIGNING_KEY_PATH: /config/signing.key
      MAIN_DB_HOST: mariadb
      MAIN_DB_USERNAME: root
      MESSAGE_DB_HOST: mariadb
      MESSAGE_DB_USERNAME: root
      RAILS_ENVIRONMENT: production
      RAILS_LOG_ENABLED: "true"
      WAIT_FOR_TIMEOUT: 90
      WAIT_FOR_TARGETS: |-
        mariadb:3306
      POSTAL_WEB_HOST: bakra.postal.pdevsecops.com
      POSTAL_WEB_PROTOCOL: https
      POSTAL_SMTP_PORT: 25
      POSTAL_WEB_PORT: 5000
      POSTAL_USERNAME: admin
      POSTAL_PASSWORD: password
      POSTAL_EMAIL: admin@example.com
      POSTAL_FIRST_NAME: Admin
      POSTAL_LAST_NAME: User
    ports:
      - "5000:5000"
      - "25:25"

  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: postal
      MARIADB_ALLOW_EMPTY_PASSWORD: 'yes'
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
