version: "3"
services:
  postal:
    image: ghcr.io/postalserver/postal:3.3.4
    depends_on:
      - mariadb
    restart: always
    command: ["bash", "-c", "echo 'Waiting for MariaDB...' && until nc -z mariadb 3306; do sleep 1; done && echo 'MariaDB is up!' && postal initialize || true && postal web-server"]
    ports:
      - "5000:5000"
      - "25:25"
    environment:
      - POSTAL_SIGNING_KEY_PATH=/config/signing.key
      - MAIN_DB_HOST=mariadb
      - MAIN_DB_USERNAME=root
      - MAIN_DB_PASSWORD=
      - MESSAGE_DB_HOST=mariadb
      - MESSAGE_DB_USERNAME=root
      - MESSAGE_DB_PASSWORD=
      - POSTAL_WEB_HOST=${POSTAL_WEB_HOST:-bakra.postal.pdevsecops.com}
      - POSTAL_WEB_PROTOCOL=${POSTAL_WEB_PROTOCOL:-https}
      - POSTAL_SECRET_KEY=${POSTAL_SECRET_KEY:-supersecretkey12345}
      - WEB_SERVER_BIND_ADDRESS=0.0.0.0
      - WEB_SERVER_PORT=5000
      - WEB_SERVER_PROTOCOL=http
      - LOGGING_STDOUT=true
    volumes:
      - postal_config:/config
    networks:
      - eggoocggcgcg4csocwo44cg8

  mariadb:
    image: mariadb:11.7.2
    restart: always
    environment:
      - MARIADB_DATABASE=postal
      - MARIADB_ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    command: --innodb-log-file-size=256M
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - eggoocggcgcg4csocwo44cg8

volumes:
  postal_config:
  mariadb_data:

networks:
  eggoocggcgcg4csocwo44cg8:
    external: true
